### ISSUE TITLE
unlimited private keys per account

### ISSUE THREAD

**Issue by combs** [CryptUp/cryptup-browser#410]
I was only able to add a third key through a hack:

- remove all but one key
- open a new tab with cryptup settings for each new key I would like to add
- add new key into each tab without refreshing

**Comment by tomholub** [comment]
You got creative there. CryptUP should be able to work with any number of keys, but I didn't surface this functionality to the UI. 

Firstly, I need to do some performance testing (conversations with 30 encrypted messages in it - it can get sluggish). As implemented, I'm not sure what the impact would be. 

Secondly, I'm trying to keep CryptUP simple/clean/straight forward, for people who are tired of all the  confusing tools out there. Having many keys in each account is not quite aligned with that goal, as CryptUP would become more confusing to use, maintain, sync etc for the user. So until I figure out how to do all this in a clean way, I have limited the amount of keys to two per account in terms of the UI.

If you find anything else that needs improving, please let me know.

**Comment by combs** [comment]
Awesome! Thank you!

**Comment by tomholub** [comment]
Happy to help, this should get into production in about a week.
