### ISSUE TITLE
re-think logo

### ISSUE THREAD

**Issue by tomholub** [CryptUp/cryptup-browser#481]

**Comment by tomholub** [comment]
I don't like the "full" CryptUp logo I designed. It seems to read CRYPR UP and looks a bit weird.

![image](https://cloud.githubusercontent.com/assets/6306961/22864923/f5c04be8-f10e-11e6-8181-6aacf323c144.png)


I kind of like the square logo for favicons, browser button and similar. But I'm flexible with it.

![image](https://cloud.githubusercontent.com/assets/6306961/22864915/c9aef8e2-f10e-11e6-9a8b-d1d3b6e06f22.png)

I renamed CryptUP to CryptUp (to make it easier to pronounce). So I wonder if maybe and arrow would do the job in the green box.

`Crypt [^] `

Or maybe make it like this

```
  Crypt
______
|    /\    |
|_____|
```

Hope that makes sense, I can do some sketches. What I mean is we can experiment with some other logos and find a better one.

**Comment by mondo989** [comment]
<img width="1253" alt="screen shot 2017-03-19 at 6 33 25 pm" src="https://cloud.githubusercontent.com/assets/3431871/24086800/5744948e-0cd3-11e7-9bee-cbce9e1eb448.png">

Playing around with different typefaces...

**Comment by tomholub** [comment]
I would conider some boxier font. Also I would still use the original UP.

The font can evolve from what we already have, just a bit more modern and readable, but still square-y

**Comment by tomholub** [comment]
Some experiments
http://www.dafont.com/squares-2.font?text=CRYPT+up&psize=s&back=theme
http://www.dafont.com/rexlia.font?text=Crypt+Up&psize=s&back=theme

![image](https://cloud.githubusercontent.com/assets/6306961/24087376/57f6e398-0cdb-11e7-821b-a930305aaeeb.png)

**Comment by mondo989** [comment]
As I am working on the landing page, I can work with complementary fonts and see if we can find one that can tie the logo's typeface and website altogether.

**Comment by tomholub** [comment]
For website we can re-use the font that we use in the plugin (Open Sans), unless you find a font that you think is a better choice. In that case I may have to change the font in the extension as well (bit of a pain to do as a lot of the text is tight-fitted to the size of the container).

For the logo, I think we'll have to adapt it into our own vector from some base font. For example, I like like the font choice "2" the most but it's weirdly choppy, as if the person doing the font got bored and released a WIP. I think a custom vector based on it would be great. A second choice would be choice "1". In either case, the font should be a tad bit slimmer, especially for choice "2".

![image](https://cloud.githubusercontent.com/assets/6306961/24176402/05fec37e-0e59-11e7-83d9-5f11da9c76eb.png)

We can of course experiment with more fonts

**Comment by mondo989** [comment]
I plan on using Open Sans so no worries on needing to squish the bugs.

Ideally I would like to pair it with another... as Open Sans everywhere on a website can be a bit boring. If we can find a good pairing font that we can also use in the logo, then it's a double whammy. (Not really expecting it to happen).

And for logo, converting it to a vector/svg, is pretty straight forward. 
Nailing the 'right typeface' for the logo font can be a bit more challenging.

**Comment by tomholub** [comment]
Ah, got it. Definitely up to try and find a good pair font to go along with Open Sans.

I don't think it will be the same font as the logo.

**Comment by tomholub** [comment]
CryptUp will be renamed to FlowCrypt. 

![image](https://cloud.githubusercontent.com/assets/6306961/25929132/20e1d1ee-35b5-11e7-862a-28ae9cdcc1f6.png)

We may fiddle with the logo to see what fits best, but for now, I'm closing this.
