### ISSUE TITLE
public profile - design + button

### ISSUE THREAD

**Issue by tomholub** [CryptUp/cryptup-browser#646]
@mondo989 let me know if you have any thoughts

There will be a public profile page where anyone can send messages and files to cryptup users. Prototype: http://cryptup.org/me/tom

Following info will be there:
 - intro text (as seen)
 - profile pic (as seen)
 - name (as seen)
 - message box (as seen)
 - "about cryptup" or better "about cryptup encryption" link (as seen)

Following will be there as well but currently missing on the page:
 - "public key" (link - will lead to a a page where people can download or copy a key. That page will look somewhat like plugin public key page. People can also link directly to it if they just want to share their pubkey)
 - phone (optional)
 - web (optional)
 - company name (optional)

**Comment by mondo989** [comment]
To better my understanding and just say it back to you... 

As a regular new user, the purpose of this page is so that I can send encrypted emails to a person (Tom for example), who prefers to communicate via PGP encrypted email. (Maybe kind of like a coinbase's individual profile pages.) And from this profile page, I can also download your public key, and any additional content you'd like to share. 

Will this public profile page allow users to bypass Gmail, in regards to sending pgp encrypted messages?

Let me know if that sounds about correct?

**Comment by tomholub** [comment]
I think that's correct. As a person who doesn't use cryptup or other software, you can send me encrypted messages.

It won't really bypass Gmail though. It's still email, so it will end up in my Gmail inbox.

**Comment by mondo989** [comment]
Cool got ya. 

I throw together some rough mocks shortly...

**Comment by tomholub** [comment]
kk :)

**Comment by mondo989** [comment]
![profile-draft 2](https://cloud.githubusercontent.com/assets/3431871/24089232/ad955148-0cf1-11e7-93d5-7a498462a58d.png)

A few thoughts:

I've segmented the content a bit.
- Putting all profile items in a contained box. (Helps to group the relevant content)
- With the Public key, I'd image when clicking the button it will copy to your keyboard.
     Clicking the down arrow will reveal the actual key, if you want to see/copy the content. 

I've bolded the 'Send tom Encrypted Emails' copy.
And moved the 'You can also have a page' to the bottom.

**Comment by tomholub** [comment]
It's a good start! I think I would have the "public key" be a link that links to another page where the key is as a default action. The down arrow will then offer
 - see details (which would also be a link to that page)
 - copy to clipboard
 - download file

"you can also have a page like this" would be in a footer. Let's copy and paste the fixed footer design from cryptup settings

I like the box but would like to experiment with it some more. maybe try the same width as email box or contain the whole thing in the box.

Lastly, there will be an "intro" message that the user can set. It can be either a single line or it could be several lines.

**Comment by tomholub** [comment]
Building on what you made:

![image](https://cloud.githubusercontent.com/assets/6306961/24119071/356f8d56-0d6d-11e7-9c20-ff7a294e091b.png)

**Comment by tomholub** [comment]
By the way, the image may also be a logo. Which means it may be horizontal - eg 80x200px, or square/circle like now. I like that the design as you made it would easily allow using wider images/logos as profile pic as well as square ones - that's awesome.

**Comment by tomholub** [comment]
some more notes
 - I guess could be a bit slimmer/less wide
 - we could move the encrypt and send button all the way below the box, as well as attach files button
 - will need different font for the title

**Comment by mondo989** [comment]
I like where you are taking it, 
let me play around with the design a bit tonight....

**Comment by tomholub** [comment]
sounds good! I'm pretty much ready to deploy the page when design is done.

**Comment by mondo989** [comment]
<img width="962" alt="screen shot 2017-03-23 at 6 58 44 pm" src="https://cloud.githubusercontent.com/assets/3431871/24277529/de91c9fa-0ffa-11e7-8b04-b6acf1093b8a.png">


Sorry for the delay on this...

**Comment by mondo989** [comment]
A few thoughts...

- Since we are having a good amount of functionality inside the 'down chevron,' of the 'Public Key' link/button. I think it makes sense to have the chevron inside of a button. We can still use the 'Public Key' side to link to the other page. Otherwise being a chevron all alone (in link form), can get overlooked. 
- I put it all inside of a container, to bring it all together. Having outside of the container, doesn't have it feel as connected.
- I think we should leave the compose buttons the way they are so that the user can become better familiar with how to use CryptUP.

Let me know any thoughts or feedback.

**Comment by tomholub** [comment]
I like it. A few thoughts:

 - would experiment more with the gradient, maybe try other gradients or
solid color
 - I think it makes sense how you approach the pubkey. The reason I prefer
no border (button) is because it makes it too prominent. Most people have
no clue what pubkey is or what it's for, and if they are future CryptUp
users, I don't want them to have to learn. It's there for people who
exactly know how to use it. I don't mind if they overlook the chevron,
because the page this will lead to will have all the same functionality
(and more). So there is no loss.
 - prefer to have the icons without circles, just the icon :) eg phone, etc
 - wish the reply box would take up the whole bottom, not leaving white
space around

It's definitely going in a good direction!

 - one last thing I would experiment with is having the profile pic
absolutely positioned on the right side, defined by space from the right
border. That way, if someone wants to use a logo that is 200x100
(horizontal), it would fit there nicely, without us having to squash the
logo

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Updates...
<img width="913" alt="screen shot 2017-03-23 at 7 29 41 pm" src="https://cloud.githubusercontent.com/assets/3431871/24278135/222ac226-0fff-11e7-8507-e5ef3604393e.png">

- Solid gray
- No border (thanks for helping me to understand your perspective on it better.)
- Updated. Once we have it confirmed, I can modify/play icons a bit more
- Updated


And not sure if I understand your request with profile image absolutely positioned on the right side?
If someone were to post a 200x100 image, couldn't we just scale down it proportionally, which make their heavily horizontal photo become 'smaller' but not squished?

**Comment by tomholub** [comment]
Yeah we could just scale it. The problem with traditional business logos
is, many are horizontal with a bunch of text (WHATEVER & PARTNERS
INVESTMENTS) and then a line below it and globe in the corner or whatever.
When we scale such logo, it will be effectively unrecognizable.

For now though, don't worry about it - let's deploy it as is and then worry
about logos later if it becomes a problem.

Looks good!

--
Tom James Holub <http://holub.me/>
