### ISSUE TITLE
public contact page - settings button and indicator

### ISSUE THREAD

**Issue by tomholub** [CryptUp/cryptup-browser#777]
Check out "Public Contact Page" link on the bottom of settings

this will become one of the tiles in cryptup settings, but it's missing a tile icon

Please make a PR where you add it to the right of NEW EMAIL

**Comment by mondo989** [comment]
@tomholub got ya. 
Will the 'Public Contact Page' also be included in the Advanced Settings as well?

**Comment by tomholub** [comment]
I think just the basic ones

**Comment by tomholub** [comment]
@mondo989 for pull requests, it's ok to work only in the Chrome directory. I have a script to copy it into Firefox as needed, and I can do that as I merge the commit.

Must be a hassle to keep them both in sync manually. It's fine to just work on Chrome only.

**Comment by tomholub** [comment]
@mondo989 one note, except in cases where it makes a lot of sense (eg the drop here overlay), please don't put user facing text into CSS. It will make it hard to make it multi-lingual down the road. Thanks!
