### ISSUE TITLE
"drop files here" overlay

### ISSUE THREAD

**Issue by tomholub** [CryptUp/cryptup-browser#778]
when someone drags a file from their computer to the compose window, it should behave similarly as Gmail - there should be some overlay that will say "drop files here"

Test gmail to see roughly what behavior it should be

Of course, when you actually drop the file, it won't work - I'll add the functionality later, but while I'm still dragging the file over the compose or reply window, the overlay should be showing.

This should also be a PR because it will make things confusing until I actually make it functional

**Comment by mondo989** [comment]
I am really happy for this.

**Comment by mondo989** [comment]
Gmail's drag-n-drop functionality for reference.

<img width="653" alt="screen shot 2017-05-28 at 10 12 22 pm" src="https://cloud.githubusercontent.com/assets/3431871/26534504/dd6205a0-43f2-11e7-908c-a92cf5562c66.png">

**Comment by mondo989** [comment]
<img width="569" alt="screen shot 2017-05-28 at 10 27 42 pm" src="https://cloud.githubusercontent.com/assets/3431871/26534707/02474f0e-43f5-11e7-8b34-78e2144cb7b1.png">

@tomholub a simpler one using familiar colors.

**Comment by tomholub** [comment]
I think we can go with this. just lowercase F and H. In other parts of the
UI I was using 4px dashed borders so you can try to experiment with that,
otherwise I think it's great

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Hey @tomholub,

To reference the "Drop files here" styling:
- Add the class ".dragging-attachment" to "div#input_text" (similar to attached).

<img width="1115" alt="screen shot 2017-05-29 at 2 12 09 pm" src="https://cloud.githubusercontent.com/assets/3431871/26558708/d744b3e4-4478-11e7-807f-62fb4bea2238.png">

<img width="589" alt="screen shot 2017-05-29 at 2 06 03 pm" src="https://cloud.githubusercontent.com/assets/3431871/26558593/ff735a56-4477-11e7-80f7-b46e02b3e5d0.png">
<img width="894" alt="screen shot 2017-05-29 at 1 59 40 pm" src="https://cloud.githubusercontent.com/assets/3431871/26558594/ff779594-4477-11e7-8643-3d3c0bcecdc5.png">
Went with 5px, as it is a bit more bold and noticable.

**Comment by mondo989** [comment]
@tomholub Let me know if you need any mods/updates here from me.

**Comment by tomholub** [comment]
no it looks good, it's just waiting for me to do the functionality before I pull it
