### ISSUE TITLE
Having to Validate my "Advanced" account multiple times

### ISSUE THREAD

**Issue by mondo989** [CryptUp/cryptup-browser#795]
This may be a bug. 

<img width="1020" alt="screen shot 2017-06-02 at 10 18 21 pm" src="https://cloud.githubusercontent.com/assets/3431871/26749823/78252e7c-47e1-11e7-9579-8b69a30af2cd.png">

I notice that I have to keep 'validating my account' to send attachments and advanced features.

**Comment by tomholub** [comment]
Did you by any chance uninstall cryptup in between these emails?

**Comment by mondo989** [comment]
You know, that's exactly it. :)

**Comment by mondo989** [comment]
Well, this does bring another question, for a user who uninstalls and installs again... 
Will they have to go through the validation process each time?

**Comment by tomholub** [comment]
Definitely. It's considered a "new device", and I have to verify that it's
actually them on that new device. Maybe there's a better way of doing that,
but for now, this is what they'll have to do.

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Got ya, it definitely makes sense. 
And it's not something critical, just making notes/issues of anything I notice
