### ISSUE TITLE
Failed trying to import my GPG private key

### ISSUE THREAD

**Issue by Lacrymology** [CryptUp/cryptup-browser#806]
I got a "bad format" error, my existing key is an rsa2048. I wonder if the problem is the difference in key length. I got the same error importing both keyfile and armored version

**Comment by tomholub** [comment]
@Lacrymology Is this during initial setup or later when adding secondary keys?

Length is definitely not an issue. Can you print the exact error? There are a few different format related errors that can mean different things.

**Comment by Lacrymology** [comment]
This was during initial setup. When adding secondary keys it happened also, both when using a binary key file and armored text directly in the text input, BUT when I selected an armored file for "importing from a file" while adding secondary keys, the resulting armored text was different but the key worked (and I can confirm the generated key was compatible)

**Comment by Lacrymology** [comment]
I decided to start over, deleted all application data, plus the backups, and re-logged in gmail, used the armored text again, and it worked properly, so I cannot reproduce the issue (but I'm pretty certain I was doing it right at first)

Sorry

**Comment by tomholub** [comment]
No worries, I'll close this one for now, if you are able to reproduce it later, feel free to comment & I'll reopen it.
