### ISSUE TITLE
Add Password-Hint to one-time-password encrypted Mails

### ISSUE THREAD

**Issue by maxschons** [CryptUp/cryptup-browser#875]
In addition to the one-time password a password hint shown in the unencrypted part of the email would be a very nice feature.

**Comment by tomholub** [comment]
@maxschons I'd suggest to use the "intro" button on top right and then add a password hint in the unencrypted intro. Let me know if that works for your use case.

**Comment by maxschons** [comment]
yes, it does, though I would appreciate an explicit 'password hint' field. It somehow seems natural to add this besides of giving an intro-statement. Nevertheless I got your point...

**Comment by tomholub** [comment]
I used to have one and actually removed it in favor of having the intro.

Going forward, I may be switching to a system that doesn't require a
password (recipient will choose their own). For now, I'll close it. Thanks
for the suggestion though!
