### ISSUE TITLE
setup information forgotten in Inbox after Chrome update

### ISSUE THREAD

**Issue by RamonBeast** [CryptUp/cryptup-browser#909]
I am noticing a weird behavior after upgrading to Chrome 60.0.3112.113.

Cryptup still correctly appears under "Apps connected to your account" on Google but everytime I try to access an encrypted email under Inbox, the email is not decrypted and when clicking on Cryptup in Chrome's toolbar, the "Setup cryptup" button appears. 

Completing the setup doesn't help since the settings appear to be "forgotten" immediately after refreshing Inbox page so it's not possible to decrypt the email (and Cryptup asks again to be setup). Under Gmail cryptup works as usual though.

**Comment by tomholub** [comment]
I just got one more report about this. I'll check what is happening with inbox.

**Comment by tomholub** [comment]
It should soon update to a new version and start working again in inbox.
